spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: westside
    username: postgres
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled=true:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
